config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :families
  resources :students do
    resources :courses
  end
  resources :teachers do
    resources :courses
  end
  resources :courses do
    resources :students
  end
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :students,  dependent: :destroy
  has_many :guardians, dependent: :destroy
  has_many :addresses, dependent: :destroy

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :students,  allow_destroy: true
  accepts_nested_attributes_for :guardians, allow_destroy: true

  belongs_to :company

  self.per_page = 15

  def self.list(params)
    results = where(company_id: params[:company_id]).search(params[:q])
    results.paginate(page: params[:page]).order(:name)
  end

  def self.search(query)
    result = includes(:students).references(:students)
    return result unless query
    result.where("name LIKE :query OR students.first_name LIKE :query",
                 {query: "%#{query}%"})
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_filter :set_company_id #make this part of login

  def index
    params[:company_id] ||= session[:company_id]
    @families = Family.list params
  end

  def show
    @family = Family.find(params[:id])
  end

  def new
    @family = Family.new
    @family.addresses.build
    @family.students.build
    @family.guardians.build
  end

  def create
    @family = Family.new(secure_params)
    @family.company_id = session[:company_id] if session[:company_id]
    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: "Family was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @family = Family.find(params[:id])
    @family.addresses.build if @family.addresses.empty?
  end

  def update
    @family = Family.find(params[:id])
    if @family.update_attributes(secure_params)
      redirect_to families_path, notice: "Family Updated."
    else
      redirect_to families_path, alert: "Unable to update family."
    end
  end

  def destroy
    family = Family.find(params[:id])
    family.destroy
    redirect_to families_path, notice: "Family deleted."
  end

  private

  def secure_params
    params.require(:family).permit(:_destroy,
                                   :name,
                                   :home_phone,
                                   :emergency_contact_name,
                                   :emergency_contact_phone,
                                   :active,
                                   addresses_attributes: [:id, :kind, :street_address,
                                                          :city, :state, :zip_code,
                                                          :_destroy],
                                   students_attributes:  [:id, :first_name, :last_name,
                                                          :mobile_phone, :email,
                                                          :allergies, :medical_information,
                                                          :birth_date, :_destroy],
                                   guardians_attributes: [:id, :first_name, :last_name,
                                                          :mobile_phone, :email,
                                                          :work_phone, :_destroy])
  end

  def set_company_id
    session[:company_id] ||= Company.where(name: "South Bay Dance Center").first.id
  end
end

app/helpers/family_helper.rb
module FamilyHelper
  def age(student)
    return "?" unless student.birth_date
    student.age
  end
end

app/views/families/_family.html.erb
<td>
  <%= link_to family.name, edit_family_path(family) %>
</td>
<td>
  <% family.students.each do |student| %>
    <%= link_to edit_student_path(student) do %>
      <%= "#{student.first_name} (#{age(student)})" %>
    <% end %><br/>
  <% end %>
</td>
<td>
  <%= link_to(edit_family_path(family), class: 'button-xs') do %>
    <span class="glyphicon glyphicon-pencil"></span>
  <% end %>
</td>
<td>
  <%= link_to(family_path(family), data: { confirm: "Are you sure?" }, method: :delete, class: 'button-xs') do %>
    <span class="glyphicon glyphicon-trash"></span>
  <% end %>
</td>

app/views/families/_form.html.erb
<%= form_for @family, html: {class: 'form-horizontal', role: 'form'} do |form| %>

  <h4><strong>Family Information</strong></h4>

  <div class="form-group">
    <%= form.label :family_name, class: 'col-xs-2 control-label' %>
    <div class="col-xs-6">
      <%= form.text_field :name, class: 'form-control', placeholder: "Family Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :home_phone, class: 'col-xs-2 control-label' %>
    <div class="col-xs-6">
      <%= form.telephone_field :home_phone, class: 'form-control', placeholder: "Home Phone" %>
    </div>
  </div>

  <%= form.fields_for :addresses do |address_form| %>
    <div class="form-group">
      <%= address_form.label :home_address, class: 'col-xs-2 control-label' %>
      <div class="col-xs-6">
        <%= address_form.text_field :street_address, class: 'form-control', placeholder: "Street Address" %>
      </div>
    </div>

    <div class="form-group">
      <%= address_form.label " ", class: 'col-xs-2 control-label' %>
      <div class="col-xs-3">
        <%= address_form.text_field :city, class: 'form-control', placeholder: "City" %>
      </div>
      <div class="col-xs-1">
        <%= address_form.text_field :state, class: 'form-control', placeholder: "State" %>
      </div>
      <div class="col-xs-2">
        <%= address_form.text_field :zip_code, class: 'form-control', placeholder: "Zip Code" %>
      </div>
      <div class="col-xs-6">&nbsp;</div>
    </div>
  <% end %>

  <h4><strong>Students</strong></h4>
  <%= form.fields_for :students do |student_form| %>
    <%= render partial: "student_fields", locals: { form: student_form } %>
  <% end %>
  <%= link_to_add_fields "Add Student", form, :students %>

  <h4><strong>Guardians</strong></h4>
  <%= form.fields_for :guardians do |guardian_form| %>
    <%= render partial: "guardian_fields", locals: { form: guardian_form } %>
  <% end %>
  <%= link_to_add_fields "Add Guardian", form, :guardians %>

  <h4><strong>Emergency Contact</strong></h4>
  <div class="row">
      <div class="col-xs-6">
        <%= form.text_field :emergency_contact_name, class: 'form-control', placeholder: "Name" %>
      </div>
      <div class="col-xs-6">
        <%= form.text_field :emergency_contact_phone, class: 'form-control', placeholder: "Phone" %>
      </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <div class="checkbox">
        <label>
          <%= form.check_box :active %> Active
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-12">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
<% end %>

app/views/families/_guardian_fields.html.erb
<div class="panel panel-default fields">
  <div class="panel-body">
    <div class="form-group">
      <%= form.label :name, class: 'col-xs-2 control-label' %>
      <div class="col-sm-3">
        <%= form.text_field :first_name, class: 'form-control', placeholder: "First Name" %>
      </div>
      <div class="col-sm-3">
        <%= form.text_field :last_name, class: 'form-control', placeholder: "Last Name" %>
      </div>
      <div class="col-sm-3 pull-right">
        <%= link_to_remove_fields "Remove Guardian", form %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :mobile_phone, class: 'col-xs-2 control-label' %>
      <div class="col-sm-6">
        <%= form.phone_field :mobile_phone, class: 'form-control', placeholder: "Mobile Phone" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :work_phone, class: 'col-xs-2 control-label' %>
      <div class="col-sm-6">
        <%= form.phone_field :work_phone, class: 'form-control', placeholder: "Work Phone" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :email, class: 'col-xs-2 control-label' %>
      <div class="col-sm-6">
        <%= form.text_field :email, class: 'form-control', placeholder: "Email" %>
      </div>
    </div>
  </div>
</div>

app/views/families/_student_fields.html.erb
<div class="panel panel-default fields">
  <div class="panel-body">
    <div class="form-group">
      <%= form.label :name, class: 'col-xs-2 control-label' %>
      <div class="col-sm-3">
        <%= form.text_field :first_name, class: 'form-control', placeholder: "First Name" %>
      </div>
      <div class="col-sm-3">
        <%= form.text_field :last_name, class: 'form-control', placeholder: "Last Name" %>
      </div>
      <div class="col-sm-3 pull-right">
        <%= link_to_remove_fields "Remove Student", form %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :mobile_phone, class: 'col-xs-2 control-label' %>
      <div class="col-sm-6">
        <%= form.phone_field :mobile_phone, class: 'form-control', placeholder: "Mobile Phone" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :birth_date, class: 'col-xs-2 control-label' %>
      <div class="col-sm-6">
        <%= form.date_field :birth_date, class: 'form-control', placeholder: :birth_date %>
      </div>
    </div>
  </div>
</div>

app/views/families/edit.html.erb
<div class="container">
  <div class="row">
    <h3>Edit <%= @family.name %> Family</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/families/index.html.erb
<div class="container">
  <div class="row">
    <h3>Families</h3>
    <%= form_tag(families_path, method: "get") do %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>
    <table class="table table-striped table-hover table-responsive">
      <thead>
        <th>Name</th>
        <th>Student(s)</th>
        <th>Edit</th>
        <th>Delete</th>
      </thead>
      <tbody>
        <% @families.each do |family| %>
          <tr>
            <%= render family %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="text-center">
  <%= will_paginate @families %>
</div>
<div class="container">
  <%= link_to("Create family", new_family_path, class: 'button-xs') %>
</div>

app/views/families/new.html.erb
<div class="container">
  <div class="row">
    <h3>New Family</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/families/show.html.erb
<div class="container">
  <div class="row">
    <h3><%= @family.name %> Family</h3>
  </div>
</div>