config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :families
  resources :students do
    resources :courses
  end
  resources :teachers do
    resources :courses
  end
  resources :courses do
    resources :students
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :company
  has_many :courses

  def self.list(params={})
    Teacher.all
  end

  def name
   "#{read_attribute(:first_name)} #{read_attribute(:last_name)}"
  end

  def work_hours
    courses.map { |c| c.duration }.sum
  end

  def payroll_hours
    work_hours * 2
  end

  def total_payroll_hours
    payroll_hours
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.list(params)
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(secure_params)
    @teacher.company_id = session[:company_id] if session[:company_id]
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: "Teacher was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    lookup_teacher
  end

  def update
    params[:teacher][:course_ids] ||= []
    lookup_teacher
    if @teacher.update_attributes(secure_params)
      redirect_to teacher_path, notice: "Teacher Updated."
    else
      redirect_to teacher_path, alert: "Unable to update teacher."
    end
  end

  private

  def secure_params
    params.require(:teacher).permit( :first_name, :last_name,
                                     { course_ids: [] } )
  end

  def lookup_teacher
    @teacher = Teacher.find(params[:id])
  end
end

app/views/teachers/_courses.html.erb
<table class="table table-hover">
  <thead>
    <th class="<%= 'hidden-xs hidden-sm' unless editable %>">Add</th>
    <th>Class Name</th>
    <th>Age</th>
    <th>Day</th>
    <th>Time</th>
    <th>Studio</th>
    <th>Status</th>
  </thead>
  <tbody>
    <% courses.each do |course| %>
      <tr class="<%= 'danger' if course.full? %>">
        <td class="<%= 'hidden-xs hidden-sm' unless editable %>">
          <%= check_box_tag "student[course_ids][]", course.id, student.courses.include?(course) %>
        </td>
        <td><%= course.name %></td>
        <td><%= "#{course.start_age} - #{course.end_age}" %></td>
        <td><%= course.day %></td>
        <td><%= "#{course.start_at.strftime('%l:%M %P')} - #{course.end_at.strftime('%l:%M %P')}" %></td>
        <td><%= course.studio %></td>
        <td><%= "Full" if course.full? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/_form.html.erb
<%= form_for @teacher, html: {class: 'form-horizontal', role: 'form'} do |form| %>

  <div class="form-group">
    <%= form.label :first_name, class: 'col-xs-2 control-label' %>
    <div class="col-xs-6">
      <%= form.text_field :first_name, class: 'form-control', placeholder: "First Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :last_name, class: 'col-xs-2 control-label' %>
    <div class="col-xs-6">
      <%= form.text_field :last_name, class: 'form-control', placeholder: "Last Name" %>
    </div>
  </div>

  <h4> Classes </h4>
  <% for course in Course.list %>
    <div>
      <%= check_box_tag "teacher[course_ids][]", course.id, @teacher.courses.include?(course) %>
      <%= course.name %> <%= course.level %> <%= course.day %> from <%= course.start_time %> to <%= course.end_time %>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-12">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>

<% end %>

app/views/teachers/edit.html.erb
<div class="container">
  <div class="row">
    <h3>Edit <%= @teacher.name %></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Teachers</h3>
    <table class="table table-hover">
      <thead>
        <th>Teacher Name</th>
        <th>Scheduled Payroll Hours</th>
        <th>Subbed Hours</th>
        <th>Total Pay Period Hours</th>
        <th>Edit</th>
      </thead>
      <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= teacher.name %></td>
            <td><%= teacher.payroll_hours %></td>
            <td> 0 </td>
            <td><%= teacher.total_payroll_hours %></td>
            <td>
              <%= link_to(edit_teacher_path(teacher), class: 'button-xs') do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="container">
  <div class="row">
    <h3>New Teacher</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="container">
  <div class="row">
    <h3><%= @teacher.first_name %> <%= @teacher.last_name %></h3>
  </div>
</div>